.PHONY : tfm_clean nspe_pre_build nspe_post_build

clean : tfm_clean

nspe_pre_build:
	cd ../../../Middleware/ARM/trusted-firmware-m && git apply ../../../Projects/b_u585i_iot02a_tfm/Src/PatchFiles/tfm.patch
	${MAKE} -f ../tfm.mk info spe_bin nspe_build_reqs

nspe_post_build:
	${MAKE} -f ../tfm.mk spe_signed nspe_signed ota update factory

pre-build : nspe_pre_build

post-build : nspe_post_build

tfm_clean:
	cd ../../../Middleware/ARM/trusted-firmware-m && git apply -R ../../../Projects/b_u585i_iot02a_tfm/Src/PatchFiles/tfm.patch
	-${RM} *.{hex,bin,elf,axf,sh,ld,c}
	-${MAKE} -f ../tfm.mk clean
