.PHONY : tfm_clean nspe_pre_build nspe_post_build

clean : tfm_clean

nspe_pre_build:
	${MAKE} -f ../tfm.mk info spe_bin nspe_build_reqs

nspe_post_build:
	${MAKE} -f ../tfm.mk spe_signed nspe_signed ota update factory

pre-build : nspe_pre_build

post-build : nspe_post_build

#secondary-outputs : nspe_post_build

tfm_clean:
	-${RM} *.{hex,bin,elf,axf,sh,ld,c}
